### ISSUE TITLE
[BUG] service := service

### ISSUE THREAD

**Issue by jlk** [nikoksr/notify#270]
Hiya. I'm digging into the source as I'm trying to figure out how to use notify, and came across this line in `send.go` that seems to have a pointless line of code at line 25:

```
		service := service
```

I can send a PR to clean up this and a few small things like comments, but just want to make sure this isn't doing something non-obvious...

**Comment by nikoksr** [comment]
Hi @jlk, thanks for taking the time to go through the project and code.

What you see there is one of the rare quirks in Go. We have to do this because we are using the loop iterator in a goroutine. I won't explain this in detail here now, but leave you with [this] (https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables=) excellent explanation from the Go wiki of what is happening here and why we need to write `service := service`

To illustrate, the first screenshot shows what the address of the iterator variable would look like at each iteration if we removed `service := service`:

![image](https://user-images.githubusercontent.com/31685472/166213709-9f878f6c-1463-4030-ad34-b684e09cd219.png)

As you can see, I commented out `service := service` and then printed the memory address of the iterator variable (`service`). In the log output you can see that the address remains the same for all ten iterations.

However, if I insert `service := service` again, we get the following as the result:

![image](https://user-images.githubusercontent.com/31685472/166214042-9e68ccd6-bf7c-4f7b-bd67-2420278e5edc.png)

Now for each iteration we get a unique memory address, each pointing to a unique service, i.e. the behavior we want.


I hope this helps!

**Comment by jlk** [comment]
huh...that's one of the stranger go quirks I've seen - thanks for the detailed explanation, @nikoksr !
