### ISSUE TITLE
[BUG] : multiple messages

### ISSUE THREAD

**Issue by itwars** [nikoksr/notify#412]
My module:

```go
package mess

import (
   "context"

   "github.com/nikoksr/notify"
   "github.com/nikoksr/notify/service/telegram"
)

func Telegram(message string) {
   telegramService, _ := telegram.New("mykey")
   telegramService.AddReceivers(1234)
   notify.UseServices(telegramService)
   _ = notify.Send(context.Background(), "", message)
}
```

My call in main.go:

```go
package main

import (
        "mod/mess"
)

func main() {
        mess.Telegram("Wtf 1 !?")
        mess.Telegram("Wtf 2 !?")
        mess.Telegram("Wtf 3 !?")
}
```

Outputs:

```txt
Wtf 1 !?
Wtf 2 !?
Wtf 2 !?
Wtf 3 !?
Wtf 3 !?
Wtf 3 !?
```

Any ideas?

**Comment by nikoksr** [comment]
Hi @itwars,

happy to see you playing around with the project! Hope you've enjoyed it so far.

The issue you're encountering here happens due to how Notify _internally_ handles services. Assigning a new service to a Notifier via, as in your example, `notify.UseServices(telegramService)` [appends](https://github.com/nikoksr/notify/blob/d2dfd108500a30270f185d0e4be60c248061773a/use.go#L11) the given service to an internal slice of services. Emphazie being on `slice`; it's not a map. Calling `notify.UseServices(telegramService)` _n_ times, results in that service being appended to the services list _n_ times.

`UseServices` should be seen as a setup function, you usually have to add a new service only once. In your example, you've embedded this initialization logic into the `mess.Telegram` function. Every time that you invoke this function, you tell Notify to add the `telegramService` list, resulting in the output you've provided. 

There are multiple approaches to solve this in your example. I'm quickly gonna list two in the following. The ideal solution would depend on your specific usecase.

#### Example 1

> This sets up the telegram service only once at initialization. Avoids redundant calls to `UseService` method.

```go
package mess

import (
	"context"

   	"github.com/nikoksr/notify"
   	"github.com/nikoksr/notify/service/telegram"
)

func init()
	telegramService, _ := telegram.New("mykey")
   	telegramService.AddReceivers(1234)
   	notify.UseServices(telegramService)
}

func Telegram(message string) {
	_ = notify.Send(context.Background(), "", message)
}
```

```go
package main

import (
	"mod/mess"
)

func main() {
	mess.Telegram("Wtf 1 !?")
  	mess.Telegram("Wtf 2 !?")
  	mess.Telegram("Wtf 3 !?")
}
```

#### Example 2

> A solution, that I'd personally prefer, would be, to not use a local Notify instance and pass it to the `Telegram` message.

```go
package mess

import (
	"context"

	"github.com/nikoksr/notify"
)

func Telegram(n notify.Notifier, message string) {
	_ = n.Send(context.Background(), "", message)
}
```

```go
package main

import (
	"github.com/nikoksr/notify"
	"github.com/nikoksr/notify/service/telegram"
	"github.com/nikoksr/test-notify/mod/mess"
)

func main() {
	// Create the telegram service here
	telegramService, _ := telegram.New("mykey")

	// Init a new Notify instance and assign the telegram service; using this constructor function for convenience, not a requirement
	n := notify.NewWithServices(telegramService)

	// Send your messages
	mess.Telegram(n, "Message 1")
	mess.Telegram(n, "Message 2")
	mess.Telegram(n, "Message 3")
}
```

I hope, that I can help you with this! Do you feel like the documentation needs to be clearer on this, or more detailed in general? Your feedback would be appreciated.

**Comment by nikoksr** [comment]
Closing this under the assumption that the issue got cleared up.

**Comment by itwars** [comment]
Hi @nikoksr,
Yes sure, it now works for me! Sorry for this late answer.
BR
Vincent
